config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'users/index'
    get 'users/show'
    get 'users/new'
    get 'users/edit'
  end
  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :posts do
    resources :likes, only: [:create, :destroy]
  end

  root 'home#top'
  get '/about', to: 'home#about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image

  validates :title, presence: true
  validates :content, presence: true, length: {maximum:140}

  belongs_to :user
  has_many :likes
  has_many :liked_users, through: :likes, source: :user

  def self.ransackable_attributes(auth_object = nil)
    %w[title content]
  end

  def self.ransackable_assosiations(auth_object = nil)
    []
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one_attached :image

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required

  private

    def current_user
      @current_user||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def login_required
      unless current_user
        flash[:notice] = "ログインが必要です"
        redirect_to login_path
      end
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :login_required

  def top
  end

  def about
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    # @posts=Post.all.order(created_at: :desc)
    @q = Post.all.ransack(params[:q])
    @posts = @q.result(distinct: true).order(created_at: :desc).page(params[:page]).per(3)
  end

  def show
    @like = Like.new
  end

  def new
    @post=Post.new
  end

  def edit
  end

  def create
    @post=current_user.posts.new(post_params)
    if @post.save
      redirect_to posts_path, notice: '投稿を作成しました!'
    else
      flash[:alert]= 'Save error!'
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: '投稿を編集しました!'
    else
      flash[:alert]= 'Save error!'
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: '投稿を削除しました!'
  end

  private
    def post_params
      params.require(:post).permit(:title, :content, :image)
    end

    def set_post
      @post=Post.find(params[:id])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required

  def new
  end

  def create
    user=User.find_by(email: session_params[:email])
    if user&.authenticate(session_params[:password])
      session[:user_id]=user.id
      redirect_to posts_path, notice: 'ログインしました！'
    else
      flash[:alert]= 'login error !!'
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to posts_path, notice:'ログアウトしました。'
  end

  private

    def session_params
      params.require(:session).permit(:email, :password)
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_current_user, only: [:edit, :update, :destroy]
  skip_before_action :login_required, only:[:new, :create]


  def index
    @users=User.all.order(created_at: :desc)
  end

  def show
  end

  def new
    @user=User.new
    @iconlabel='new'
  end

  def edit
    @iconlabel=nil
  end

  def create
    @user=User.new(user_params)
    @user.admin=false
    if @user.save
      session[:user_id]=@user.id
      redirect_to posts_path, notice: 'ユーザー登録が完了しました!'
    else
      flash[:alert]= 'Save error!'
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to users_path, notice: 'ユーザー登録が完了しました!'
    else
      flash[:alert]= 'Save error!'
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, notice: 'ユーザーを削除しました!'
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
    end

    def set_user
      @user=User.find(params[:id])
    end

    def require_current_user
      unless current_user.admin
        unless current_user.id==params[:id].to_i
          flash[:notice]="権限がありません。"
          redirect_to user_path(current_user)
        end
      end
    end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<div class="p-5 mt-5 bg-light shadow">
  <div class="row mb-4">
    <div class="col-md-8 mb-3">
      <h3 class="mb-3">Apo_Tweetについて</h3>
      <p class="read">Apo_Tweet（アポツイート）は、アポサイバーが運営する、投稿サイトです。アポはアメリカンショートヘアーという種類の猫です。このアポがサイバー事業に投資したベンチャービジネスがアポサイバーなのです。空間を自由に行き来し、2030年の近未来から、人間の頭脳を遥かに超えた存在として、この2021年に現れました。</p>
      <p class="read">最高に楽しい時間と空間を楽しんでください。夢みがちなあなたにきっと満足いただける投稿サイトに仕上がっています。これからの自由な時間をゆっくりとお過ごしください。</p>
      <div class="pt-5">
        <h3><span class="badge bg-secondary">wonder land</span>
        <span class="badge bg-secondary">never land</span></h3>
      </div>
    </div>
    <div class="col-md-4">
      <%= image_tag '/apo.jpg', class:"img-fluid", alt:"Apoの写真" %>
    </div>
</div>

app/views/home/top.html.erb
<div class="py-4">
  <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="river.jpg" class="d-block w-100" alt="sorry no picture">
        <div class="carousel-caption d-none d-md-block">
          <h1 class="display-4">Apo_Tweetへようこそ</h1>
          <p class="lead">これは、いろんな人々が投稿するサイトです！</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="sunset.jpg" class="d-block w-100" alt="sorry no picture">
        <div class="carousel-caption d-none d-md-block">
          <h1 class="display-4">Apo_Tweetを訪れた人へ</h1>
          <p class="lead">ようこそ、いらっしゃいました　歓迎します！！</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="mountain.jpg" class="d-block w-100" alt="sorry no picture">
        <div class="carousel-caption d-none d-md-block">
          <h1 class="display-4">Apo_Tweetを始めよう！！</h1>
          <p class="lead">きっと、きっと、楽しんでいただけるでしょう</p>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>

<div class="py-4">
  <div class="container">
    <div class="row">
      <div class="col-md-2">
        <h3>News</h3>
      </div>
      <div class="col-md-10">
        <dl class="row">
          <dt class="col-md-3 fw-bold text-primary">2021年10月09日</dt>
          <dd class="col-md-9 fw-bold text-primary">検索機能の不具合の改善、ログイン後もAbout us表示</dd>
          <dt class="col-md-3 ">2021年9月20日</dt>
          <dd class="col-md-9 ">待望のApo＿Tweetのトップページ</dd>
          <dt class="col-md-3">2021年8月15日</dt>
          <dd class="col-md-9">blogのような投稿サイトようなHP</dd>
          <dt class="col-md-3">2021年8月01日</dt>
          <dd class="col-md-9">さて少しづつ作成開始</dd>
        </dl>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>

  </head>

  <body>
    <header class="py-2">
      <div class="container text-center">
        <%= image_tag "/apo_cyber.jpg", width: '10%', alt: "Apo_Post" %>
      </div>
    </header>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top" role="navigation">
      <div class="container">
        <%= link_to 'Apo_Tweet', root_path, class:"navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ">
            <% if current_user %>
               <li class="nav-item">
                <%= link_to 'About us', about_path, class:"nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to '投稿一覧', posts_path, class:"nav-link" %>
              </li>
              <li class="nav-item">
                  <%= link_to '新規投稿', new_post_path(current_user), class:"nav-link" %>
              </li>
              <li class="nav-item">
                  <%= link_to 'ユーザー一覧', users_path, class:"nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to 'ログアウト', logout_path, method: :delete, class:"nav-link" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'About us', about_path, class:"nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to '新規登録', new_user_path, class:"nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to 'ログイン', login_path, class:"nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
        <div  class="fw-bold text-white ml-auto"><%= 'ログインユーザー：' + current_user.name if current_user %></div>
      </div>
    </nav>

    <div class="container">
    <% if flash.notice.present? %>
      <div class="alert alert-success"><%= flash.notice %></div>
    <% end %>
    <% if flash.alert.present? %>
      <div class="alert alert-danger"><%= flash.alert %></div>
    <% end %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.present? %>
  <div class="alert alert-info">
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </div>
<% end %>

<%= form_with model: @post, local: true do |f| %>
  <div class="form-group mb-3">
    <%= f.label :title %>
    <%= f.text_field :title, class:"form-control"%>
  </div>
  <div class="form-group mb-3">
    <%= f.label :content %>
    <%= f.text_area :content, size: "50x10", class:"form-control" %>
  </div>
  <div class="form-group mb-4">
    <%= f.label :image %>
    <%= f.file_field :image, class:"form-control" %>
  </div>
  <div class="d-grid gap-2 d-md-flex justify-content-md-end mb-3">
    <%= f.submit nil, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1 class="text-center text-muted my-3">投稿の編集</h1>

<div class="my-4 py-4 bg-light shadow">
  <div class="row justify-content-md-center">
    <div class="col-md-8">
      <%= render 'form', locals: {post: @post} %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<h1 class="text-center text-muted my-3">投稿一覧</h1>


    <%= search_form_for @q, class: 'mb-5' do |f| %>
      <div class="row justify-content-md-center py-3">
        <div class="col-md-1">
          <%= f.submit class: 'btn btn-outline-primary' %>
          <i class="bi bi-search"></i>
        </div>
        <div class="form-group col-md-6">
        <!-- <%= f.label :title_or_content_cont, '検索：' %> -->
          <%= f.search_field :title_or_content_cont, class: 'form-control '%>
        </div>

    <% end %>

  <div class="row justify-content-md-center">
    <div class="col-md-8">
      <div class="mt-4 pagination flex-wrap">
        <%= paginate @posts, theme: 'bootstrap-5' %>
        <!-- <%= page_entries_info @posts %> -->
      </div>

      <% @posts.each do |post| %>
        <div class="shadow p-3 mb-1 bg-body rounded">
          <div class="col-1 float-start">
            <%= image_tag post.user.image, class:"rounded-circle w-50" if post.user.image.attached? %>
          </div>
          <h5><%= link_to post.user.name, user_path(post.user),class:"text-decoration-none text-black"%></h5>
          <div class="fw-bold"><%= link_to post.title, post_path(post) %></div>
          <%= post.content%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<h1 class="text-center text-muted my-3">投稿する</h1>

<div class="my-4 py-4 bg-light shadow">
  <div class="row justify-content-md-center">
    <div class="col-md-8">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="my-4 py-4 bg-light shadow">
  <div class="row justify-content-md-center">
    <div class="col-md-8 shadow p-5 bg-body rounded overflow-scroll">
      <%= auto_link(simple_format(h(@post.content), {}, sanitize: false, wrapper_tag: "h3")) %>
      <div class="text-muted my-3"><%=@post.created_at%></div>
        <% if current_user.already_liked?(@post) %>
          <%= button_to 'いいねを取り消す', post_like_path(@post), method: :delete %>
          <i class="bi bi-hand-thumbs-up-fill", style="font-size: 1.5rem; color: red;"></i>
        <% else %>
          <%= button_to 'いいね', post_likes_path(@post) %>
          <i class="bi bi-hand-thumbs-up", style="font-size: 1.5rem;"></i>
        <% end %>
        <span class="fs-3 fw-bold" ><%= @post.likes.count %></span>

        <!--<h2>いいねしたユーザー</h2>
        <% @post.liked_users.each do |user| %>
          <li><%= user.name %></li>
        <% end %> -->

      <%= image_tag @post.image, class:"img-fluid" if @post.image.attached? %>
      <div class="d-grid gap-2 d-md-flex justify-content-md-end mt-4">
        <% if @post.user.id==current_user.id %>
          <%= link_to '編集', edit_post_path(@post), class:"btn btn-primary" %>
          <%= link_to '削除', post_path(@post), method: :delete, data: {confirm: "削除します　よろしいですか?"}, class:"btn btn-danger" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<% if user.errors.present? %>
  <div class="alert alert-info">
    <% user.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  </div>
<% end %>

<%= form_with model: user, local: true do |f| %>
  <div class="form-group mb-3">
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="form-group mb-3">
    <%= f.label :email %>
    <%= f.text_field :email, class:"form-control" %>
  </div>
  <div class="form-group mb-3">
    <%= f.label :image %>
    <%= f.file_field :image, class:"form-control" %>
  </div>
  <% if iconlabel=='new' %>
    <div class="form-group mb-3">
      <%= f.label :password %>
      <%= f.password_field :password, class:"form-control" %>
    </div>
    <div class="form-group mb-3">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class:"form-control" %>
    </div>
  <% end %>
  <div class="d-grid gap-2 d-md-flex justify-content-md-end mb-3">
    <%= f.submit nil, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1 class="text-center text-muted my-3">アカウント編集</h1>

<div class="my-4 py-4 bg-light shadow">
  <div class="row justify-content-md-center">
    <div class="col-md-8">

      <%= render partial: 'form', locals: {user: @user, iconlabel: @iconlabel} %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1 class="text-center text-muted my-3">ユーザー一覧</h1>

<div class="my-4 py-4 bg-light shadow">
  <div class="row justify-content-md-center">
    <div class="col-md-6">
      <% @users.each do |user| %>
        <div class="shadow p-3 mb-1 bg-body rounded">
          <div class="col-2 float-start">
            <%= image_tag user.image, class:"rounded-circle w-25" if user.image.attached? %>
          </div>
          <div class="fw-bold">
            <%= link_to user.name, user_path(user), class:"text-decoration-none text-black"%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1 class="text-center text-muted my-3">新規ユーザー登録</h1>

<div class="my-4 py-4 bg-light shadow">
  <div class="row justify-content-md-center">
    <div class="col-md-8">
      <%= render partial: 'form', locals: {user: @user, iconlabel: @iconlabel} %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1 class="text-center text-muted my-3">アカウント詳細</h1>

<div class="my-4 py-4 bg-light shadow">
  <div class="row justify-content-md-center">
    <div class="col-md-8">
      <%= image_tag @user.image, class:"rounded mx-auto d-block w-25" if @user.image.attached? %>
      <h2 class='text-center'><%= @user.name %></h2>
      <p class='text-center'><%= @user.email %></p>
      <% if @user.id == current_user.id  || current_user.admin==true %>
        <div class="d-grid gap-2 d-md-flex justify-content-md-center mb-3">
          <%= link_to '編集', edit_user_path(@user), class:"btn btn-primary" %>
          <%= link_to '削除', user_path(@user), method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-danger" %>
        </div>
      <% end %>

      <div class="py-4">
      <!-- Nav tabs -->
        <ul class="nav nav-tabs" id="myTab" role="tablist">
          <li class="nav-item" role="presentation">
            <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">投稿</button>
          </li>
          <li class="nav-item" role="presentation">
            <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button" role="tab" aria-controls="profile" aria-selected="false">いいね</button>
          </li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
          <div class="tab-pane active border border-top-0" id="home" role="tabpanel" aria-labelledby="home-tab">
            <% @user.posts.each do |post| %>
              <div class="shadow p-3 mb-1 bg-body rounded">
                <div class="col-2 float-start">
                  <%= image_tag @user.image, class:"rounded-circle w-25" if @user.image.attached? %>
                </div>
                <div class="py-1">
                   <%= link_to post.content, post_path(post), class:"text-decoration-none text-black"%>
                </div>
              </div>
            <% end %>
          </div>
          <div class="tab-pane" id="profile" role="tabpanel" aria-labelledby="profile-tab">
            <% @user.liked_posts.each do |post| %>
              <div class="shadow p-3 mb-1 bg-body rounded">
                <div class="col-1 float-start">
                  <%= image_tag post.user.image, class:"rounded-circle w-50" if post.user.image.attached? %>
                </div>
                <h5><%= link_to post.user.name, user_path(post.user),class:"text-decoration-none text-black"%></h5>
                <div class="fw-bold"><%= link_to post.title, post_path(post) %></div>
                <%= post.content%>
              </div>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>